name: <malaWeb>

channels:
  - defaults
  - conda-forge

dependencies:
  - python>=3.9
  -  conda-forge::dash~=2.17.1
  -  numpy~=1.26.4
  -  conda-forge::dash-bootstrap-components~=1.4.0
  -  conda-forge::pandas~=2.2.2
  -  conda-forge::setuptools~=68.0.0
  -  conda-forge::packaging==21.0.0
  -  conda-forge::gunicorn~=20.1.0
  -  pip
  -  pip:
      - dash_uploader==0.7.0a1
      - ase~=3.23.0
